# ─── ohmyposh  ────────────────────────────────────────────────────╯

"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 4
final_space = true

[[blocks]]
  type = "prompt"
  alignment = "left"

  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "p:blue"
    template = "{{ .Path }} "

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'agnoster_short'
      max_depth = 3

  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "p:lavender"
    template = """git: {{ .HEAD }}\
      {{ if .Working.Changed }}*{{ end }}\
      {{ if .Staging.Changed }}+{{ end }}\
    """

      [blocks.segments.properties]
        branch_icon = ''
        fetch_status = true
        fetch_upstream_icon = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "p:closer"
    template = "·"

[palette]
  os = "#ACB0BE"
  closer = "p:os"
  pink = "#F4B8E4"
  lavender = "#BABBF1"
  blue = "#8CAAEE"
